# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('pages', '0004_auto_20170411_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='permitted_groups',
            field=models.ManyToManyField(blank=True, help_text='Limit viewing permission to these groups.', to='auth.Group', verbose_name='Permitted groups'),
        ),
    ]
