# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20151026_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.TextField(verbose_name='Label'),
        ),
    ]
